###
GET http://localhost:8080/thread/safe/01
###
GET http://localhost:8080/thread/safe/0
###
GET http://localhost:8080/thread/safe/01
###
GET http://localhost:8080/thread/safe/01
###
GET http://localhost:8080/thread/safe/01
###
GET http://localhost:8080/thread/safe/01
###
GET http://localhost:8080/thread/safe/01
###
GET http://localhost:8080/thread/safe/01
###
GET http://localhost:8080/thread/safe/01